# Generated by Django 5.1.5 on 2025-02-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
