# Generated by Django 5.1.5 on 2025-02-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0005_order_total_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
